In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import gc

### 1、读取 MNIST 数据：加载并处理手写数字图像数据及其对应的标签

In [4]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784',version=1, cache=True)
X,y=mnist['data'],mnist['target']

C:\Users\19297\anaconda3\envs\tensorflow\lib\site-packages\sklearn\datasets\_openml.py:56: RuntimeWarning: Invalid cache, redownloading file
  warn("Invalid cache, redownloading file", RuntimeWarning)


In [5]:
X.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel781  pixel782  pixel783  pixel784  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

### 2、特征缩放：对图像数据进行标准化处理，缩放到[0,1]范围。。

In [13]:
from sklearn.preprocessing import scale
x = scale(X)

### 3、划分训练集和测试集：将图像数据划分为训练集和测试集

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.70, random_state=101)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(49000, 784)
(21000, 784)
(49000,)
(21000,)


### 4、构建支持向量机模型，训练模型，并给出性能评价

（1）线性核 模型训练

In [17]:
from sklearn import svm
from sklearn import metrics


svm_linear = svm.SVC(kernel='linear')

svm_linear.fit(x_train, y_train)
predictions = svm_linear.predict(x_test)
metrics.accuracy_score(y_true=y_test, y_pred=predictions)


0.9211904761904762

模型评估，给出混淆矩阵、准确率、召回率、F1 值等指标

In [26]:
from sklearn.metrics import confusion_matrix
y_true=y_test
y_pred=predictions
# 计算混淆矩阵
cm = confusion_matrix(y_true, y_pred)

print("混淆矩阵：\n", cm)
from sklearn.metrics import classification_report

# 计算分类报告
report = classification_report(y_true, y_pred)

print("分类报告：\n", report)


混淆矩阵：
 [[2070    1    9    2    3   23   14    3    8    2]
 [   0 2275    4    7    1    4    1    7   12    4]
 [  18   38 1919   39   22   10   20   24   34    3]
 [  13   12   57 1943    3   62    1   11   34    9]
 [   6    9   28    4 1848    4   10   10    6   61]
 [  25   11   21   91   10 1653   32    4   24   19]
 [  22    7   40    0   20   28 1946    1    2    0]
 [   4    7   25   26   29    4    0 2084    9   52]
 [  20   41   33   61   12   39   13    9 1753   19]
 [   9   11   10   26   80    8    0   78   20 1854]]
分类报告：
               precision    recall  f1-score   support

           0       0.95      0.97      0.96      2135
           1       0.94      0.98      0.96      2315
           2       0.89      0.90      0.90      2127
           3       0.88      0.91      0.89      2145
           4       0.91      0.93      0.92      1986
           5       0.90      0.87      0.89      1890
           6       0.96      0.94      0.95      2066
           7       0.9

（2）径向基函数核

In [27]:
svm_rbf = svm.SVC(kernel='rbf')
svm_rbf.fit(x_train, y_train)
predictions = svm_rbf.predict(x_test)
print(metrics.accuracy_score(y_true=y_test, y_pred=predictions))

0.9645714285714285


模型评估

In [28]:
from sklearn.metrics import confusion_matrix
y_true=y_test
y_pred=predictions
# 计算混淆矩阵
cm = confusion_matrix(y_true, y_pred)

print("混淆矩阵：\n", cm)
from sklearn.metrics import classification_report

# 计算分类报告
report = classification_report(y_true, y_pred)

print("分类报告：\n", report)

混淆矩阵：
 [[2100    2    4    1    1    7   10    5    4    1]
 [   0 2277    9    7    2    0    1   10    3    6]
 [  14    7 2047   13    4    2    2   28   10    0]
 [   2    5   28 2032    2   24    0   23   23    6]
 [   3    5   11    0 1912    5    7    9    4   30]
 [   5    1    5   33    5 1792   21   17    5    6]
 [   9    3    4    1    2    9 2019   16    2    1]
 [   3    6   12    0   11    0    0 2186    1   21]
 [   7   16    9   20    6   13    7   12 1897   13]
 [   3    5    2   14   22    3    1   46    6 1994]]
分类报告：
               precision    recall  f1-score   support

           0       0.98      0.98      0.98      2135
           1       0.98      0.98      0.98      2315
           2       0.96      0.96      0.96      2127
           3       0.96      0.95      0.95      2145
           4       0.97      0.96      0.97      1986
           5       0.97      0.95      0.96      1890
           6       0.98      0.98      0.98      2066
           7       0.9

根据以上结果，径向基函数核的训练结果在准确率，精确率，召回率等各个指标上都好于线性核函数。